services:
  - type: web
    name: aaaatube
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
  
